version: "2"
services:
  sip.orchestrator:
    image: ibmcom/voice-gateway-so:latest
    container_name: voice-gateway-so
    ports:
      - "5060:5060"
      - "5060:5060/udp"
    environment:
      # Host name of the CMR.
      - MEDIA_RELAY_HOST=media.relay:8080
      - SIP_HOST=${EXTERNAL_IP}

      - WATSON_CONVERSATION_TOKEN_SERVICE_PROVIDER_URL=https://iam.bluemix.net/identity/token
      - WATSON_CONVERSATION_API_VERSION=v2

      # Watson Assistant Configuration
      - WATSON_CONVERSATION_APIKEY=${ASSISTANT_APIKEY}
      - WATSON_CONVERSATION_URL=${ASSISTANT_URL}
      - WATSON_ASSISTANT_ID=${ASSISTANT_SKILL_ID}

      # Logging related variables
      - ENABLE_TRANSCRIPTION_AUDIT_MESSAGES=true
      - LOG_LEVEL=all
    #volumes: #Some how this is giving java permissions error 
    #  - ./logs:/logs

  media.relay:
    image: ibmcom/voice-gateway-mr:latest
    container_name: voice-gateway-mr
    ports:
      - "16384-16394:16384-16394/udp"
    environment:
      - SDP_ADDRESS=${EXTERNAL_IP}
      - RTP_UDP_PORT_RANGE=16384-16394
      - MEDIA_RELAY_LOG_LEVEL=DEBUG
      - MEDIA_RELAY_WS_PORT=8080

      # Speech To Text configuration
      - WATSON_STT_APIKEY=${SPEECH_TO_TEXT_APIKEY}
      - WATSON_STT_TOKEN_SERVICE_PROVIDER_URL=https://iam.bluemix.net/identity/token
      - WATSON_STT_URL=${SPEECH_TO_TEXT_URL}

      # Text To Speech configuration
      - WATSON_TTS_APIKEY=${TEXT_TO_SPEECH_APIKEY}
      - WATSON_TTS_TOKEN_SERVICE_PROVIDER_URL=https://iam.bluemix.net/identity/token
      - WATSON_TTS_URL=${TEXT_TO_SPEECH_URL}
      - WATSON_TTS_VOICE=en-US_MichaelVoice
      # Uncomment the following three lines to enable call recording
      #- ENABLE_RECORDING=true
    #volumes:
    #  - ./logs:/logs
    #- $PWD/recordings:/vgw-media-relay/recordings
    # /host/path:/container/path:Z